language: cpp
compiler:
  - gcc
before_install: ./scripts/travis/install-deps.sh
install: ./scripts/travis/install-boost.sh
env:
  global:
    - BOOST_INCLUDES=/usr/local/include
    - BOOST_LIBS=/usr/local/lib
script: scons && scons test
branches:
  only:
    - master
